inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key id'
    required: true

  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key'
    required: true

  R2_ENDPOINT:
    description: 'R2 Endpoint'
    required: true

  APP_NAME:
    description: 'App name to execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build app
      run: pnpm nx run @gang-of-front/${{ inputs.APP_NAME }}:build
      shell: bash
    
    - name: Sync files
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        R2_ENDPOINT: ${{ inputs.R2_ENDPOINT }}
      run: pnpm nx run @gang-of-front/${{ inputs.APP_NAME }}:sync --dist dist --hash="${GITHUB_SHA:0:7}" --bucket=demo-gangoffront-com --s3Endpoint="${R2_ENDPOINT}" --environment=prod
      shell: bash

    - name: Update import map
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        R2_ENDPOINT: ${{ inputs.R2_ENDPOINT }}
      run: pnpm nx run @gang-of-front/${{ inputs.APP_NAME }}:update-import-map --hash="${GITHUB_SHA:0:7}" --bucket=demo-gangoffront-com --s3Endpoint="${R2_ENDPOINT}" --domainBucket='https://assets.gangoffront.com' --remoteVerify=false --environment=prod
      shell: bash
