name: 'nx-affected'
description: 'Github action for outputting a list of affected nx projects'

outputs:
  affected:
    value: ${{ steps.checkForAffected.outputs.affected }}
    description: array of affected projects (apps/libs) names
  hasAffected:
    value: ${{ steps.checkForAffected.outputs.hasAffected }}
    description: true/false if there are affected projects (apps/libs)

runs:
  using: "composite"
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      id: setSHAs
      uses: nrwl/nx-set-shas@v3
  
    - name: Check for Affected Projects
      uses: gang-of-front/action-nx-affected-list@main
      id: checkForAffected
      with:
        base: ${{ steps.setSHAs.outputs.base }}
        head: ${{ steps.setSHAs.outputs.head }}
