name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_publish:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile --prefer-offline
      - run: pnpm --filter root build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish apps/root/dist --project-name=demo-gangoffront-com
