name: Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  affected:
    runs-on: ubuntu-latest
    environment:
      name: staging
    outputs:
      affected: ${{ steps.checkForAffected.outputs.affected }}
      hasAffected: ${{ steps.checkForAffected.outputs.hasAffected }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup & Install
        uses: ./.github/actions/setup-install

      - name: Check for Affected Projects
        uses: ./.github/actions/affected
        id: checkForAffected

  replay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup & Install
        uses: ./.github/actions/setup-install

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - run: npx @puppeteer/replay user-flows

  articles-app:
    needs: [affected]
    if: contains(needs.affected.outputs.affected, 'articles-app')
    uses: ./.github/workflows/workflow-mfe.yaml
    secrets: inherit
    with:
      appName: articles-app
      environment: staging

  footer-app:
    needs: [affected]
    if: contains(needs.affected.outputs.affected, 'footer-app')
    uses: ./.github/workflows/workflow-mfe.yaml
    secrets: inherit
    with:
      appName: footer-app
      environment: staging

  header-app:
    needs: [affected]
    if: contains(needs.affected.outputs.affected, 'header-app')
    uses: ./.github/workflows/workflow-mfe.yaml
    secrets: inherit
    with:
      appName: header-app
      environment: staging

  profile-app:
    needs: [affected]
    if: contains(needs.affected.outputs.affected, 'profile-app')
    uses: ./.github/workflows/workflow-mfe.yaml
    secrets: inherit
    with:
      appName: profile-app
      environment: staging

  root-app:
    needs: [affected]
    if: contains(needs.affected.outputs.affected, 'root')
    uses: ./.github/workflows/workflow-mfe.yaml
    secrets: inherit
    with:
      appName: root
      environment: staging
