name: Workflow MFE

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true
      R2_ENDPOINT: 
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup & Install
        uses: ./.github/actions/setup-install

      - name: Build & Deploy
        uses: ./.github/actions/build-deploy-mfe
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          APP_NAME: ${{ inputs.appName}}
